Added RelatedVideos Parsing.
s-frei/TrackSearch pull request #93
Opened 2022-10-13 12:05 UTC by MrF1yn

2022-10-14 09:11 UTC, s-frei commented on library/src/main/java/io/sfrei/tracksearch/tracks/deserializer/YouTubeTrackDeserializer.java
> +        if (title==null)
We should use the `JsonElement` functionality here.

2022-10-14 09:17 UTC, s-frei requested changes
Good first shot but seems to be an incomplete implementation. Either add the *SoundCloud* related functionality or make this just exclusive for the `YouTubeClient`.

Please add tests for this!

2022-10-14 09:17 UTC, s-frei commented on library/src/main/java/io/sfrei/tracksearch/tracks/deserializer/YouTubeTrackDeserializer.java
> +        if (!owner.present()){
Same as above. Maybe extend the `JsonElement`.

2022-10-14 09:17 UTC, s-frei commented on library/src/main/java/io/sfrei/tracksearch/tracks/deserializer/YouTubeTrackDeserializer.java
>      public YouTubeTrack deserialize(final JsonParser p, final DeserializationContext ctxt) throws IOException {
Revert the fromatting changes please.

2022-10-14 09:17 UTC, s-frei commented on library/src/main/java/io/sfrei/tracksearch/clients/youtube/YouTubeService.java
> +    Call<ResponseWrapper> getVideoPage(@Query("v") String search,
Passed `String` should be named `videoID`.

2022-10-14 09:17 UTC, s-frei commented on library/src/main/java/io/sfrei/tracksearch/clients/soundcloud/SoundCloudClient.java
> +    public TrackList<YouTubeTrack> getRelatedTracks(@NonNull String videoID) throws TrackSearchException {
The `SoundCloudClient` shouldn't offert anything related to *YoutTube*

2022-10-14 09:17 UTC, s-frei commented on library/src/main/java/io/sfrei/tracksearch/clients/soundcloud/SoundCloudClient.java
> +    public TrackList<YouTubeTrack> getRelatedTracks(@NonNull String videoID) throws TrackSearchException {
*SoundCloud* has also the *related tracks*, this should be added.

2022-10-14 09:17 UTC, s-frei commented on library/src/main/java/io/sfrei/tracksearch/clients/MultiSearchClient.java
> +    public TrackList<YouTubeTrack> getRelatedTracks(@NonNull String videoID) throws TrackSearchException {
This shouldn't appear here...

2022-10-14 09:19 UTC, s-frei commented
Related feature request: #91

2022-10-14 09:22 UTC, s-frei commented
It would also be pretty convenient to get the related track from another track 😉 
Will have a look at this later...

2022-10-14 09:31 UTC, MrF1yn commented on library/src/main/java/io/sfrei/tracksearch/tracks/deserializer/YouTubeTrackDeserializer.java
>      public YouTubeTrack deserialize(final JsonParser p, final DeserializationContext ctxt) throws IOException {
Didn't understand this.

2022-10-14 09:32 UTC, MrF1yn commented
Alr thanks for the feedbacks.

2023-01-25 08:31 UTC, s-frei commented
As there is no update on this... Maybe picking this anytime later.

2023-01-25 08:31 UTC, closed without merging